### ISSUE TITLE
Can’t import new dictionary

### ISSUE THREAD

**Issue by miyamotoRyu** [mathewthe2/immersion_reader#45]
![Image](https://github.com/user-attachments/assets/7dee2435-7741-46d2-ae65-0050875024d8)

Все словари, которые я пытаюсь импортировать останавливаются на этапе «extracting dictionary 50%», и дальше не продвигаются, но некоторые словари останавливаются на этапе « extracting dictionary 1-10%»

**Comment by mathewthe2** [comment]
What kind of dictionaries are you importing?

Note that dictionaries with `structured-content` are not supported currently.

**Comment by mathewthe2** [comment]
There are differences in implementation, so I can't identify the issues without the dictionary data, or which dictionaries are causing issues. 

The android version is getting an update soon once the play store approves the latest version.

**Comment by miyamotoRyu** [comment]
Я удалил и скачал приложение заново, 2 словаря загрузил и проблема снова вернулась. Проблема касается абсолютно любого словаря, даже если они раньше у меня уже были импортированы

**Comment by mathewthe2** [comment]
What is your iOS version and device?

Can you add the dictionaries here from this link?
https://github.com/FooSoft/yomichan?tab=readme-ov-file#dictionaries

**Comment by miyamotoRyu** [comment]
iPhone 8 ver. 16.7.10

И ещё, сейчас заметил, что на андроид устройстве перестали работать после последнего обновления JP-RU словари

**Comment by miyamotoRyu** [comment]
Попробовал добавить словарь из этой ссылки, проблема та же

**Comment by miyamotoRyu** [comment]
Можно ли скачать старую версию (январь-февраль 2025) на андроид?

**Comment by miyamotoRyu** [comment]
Я думаю, что все эти проблемы связаны с последними обновлениями. Я заметил вот что:
JP-JP словари, даже без structured-content не работают нормально на IOS и Android, когда.
JP-EN словари работают хорошо на IOS и Android.
JP-RU хорошо работают на IOS, но на Android перестали работать, и сейчас не работают.
Словари нормально добавляются на Android, но на IOS, как я говорил в ливерах выше, не добавляются. 

Все эти проблемы появились после последних обновлений, раньше на обоих устройствах все нормально работало.

**Comment by mathewthe2** [comment]
> Можно ли скачать старую версию (январь-февраль 2025) на андроид?

The current version on the play store is still the first version I released back in 2024. The updates have not been live yet.

> iPhone 8 ver. 16.7.10

I'll have to install v16 on a new emulator to test it. I can try later this week.

**Comment by miyamotoRyu** [comment]
[JA-EN Onomatopoeia
[JA-EN] NEW 斎藤和英大辞典
[JA-EN] 新和英
[JA-EN] Babylon

Возможно эти словари являются причиной сбоя импорта на iOS

**Comment by mathewthe2** [comment]
新和英 working on iPhone 15 Pro (iOS 17.5)

It's possible the recent changes in the `cleanup` process have messed up the app's storage once a problematic dictionary is imported. I will release a new version soon that runs cleanup if there are errors.

<img width="347" alt="Image" src="https://github.com/user-attachments/assets/5e5dd2fb-b255-4afb-a151-3975dbf8c294" />

<img width="347" alt="Image" src="https://github.com/user-attachments/assets/5d0b6403-a7bc-4275-8164-5b17003a10d3" />

**Comment by gamrah** [comment]
Hi, I assume you're still aware of the issue but some dictionaries are still hanging on 'parsing' when they import. It was working at one point, but the last couple of updates have been a no-go for some dictionaries, probably for the reasons you've mentioned above.

**Comment by mathewthe2** [comment]
> Hi, I assume you're still aware of the issue but some dictionaries are still hanging on 'parsing' when they import. It was working at one point, but the last couple of updates have been a no-go for some dictionaries, probably for the reasons you've mentioned above.

If the issues still persist in the newer versions, unfortunately this may mean the database is corrupted and you will have to reinstall the app.

**Comment by gamrah** [comment]
Just tried it on a fresh install and it's still hanging on parsing. This was with Pixiv, Pixiv light as well as a few of the other culprits that worked on a previous version.

**Comment by mathewthe2** [comment]
Which version of pixiv and pixiv light are you using? The latest ones contain `structured-content`, which are not supported currently.

**Comment by gamrah** [comment]
Now that you mention it, it was a pretty hack-y way to get those dictionaries in to begin with (had to open, re-open the app). I missed the part about structured-content, not sure how to delineate without opening each dictionary but that’s a me problem. I’ll find some other dictionaries and get back to it, thanks!

**Comment by mathewthe2** [comment]
> Will structured-content be ever supported? [Jitendex ](https://jitendex.org/) is pretty popular with the learning community. I'm assuming it's structured-content because it parses indefinitely. Would love to buy the app in the future with this

I was planning to integrate the structured-content support that the newer jidoujisho would have, but it seems [the author has gone awol](https://github.com/arianneorpilla/jidoujisho/pull/389#issuecomment-2204766111). I would like to avoid doing repeated work if possible. There are other features I would like to work on, such as the search feature which no one prior to [myself](https://github.com/ttu-ttu/ebook-reader/issues/239#issuecomment-2869780741) has tackled yet.

I wouldn't mind looking into it if someone raised a PR draft.

Also, when you mean buying the app...do you mean buying the feature for the browser? The app is FOSS currently. I do intend to add some optional paid services in the future.

**Comment by JDoga** [comment]
No matter which dictionary I try, none of them will install. I’m using iOS, and it always gets stuck at "parsing dictionary" I don't know if there’s a concrete fix for this.
